INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL) VALUES (1, 'id1', 'pass', 'name1', 'a@a');
INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL) VALUES (2, 'id2', 'pass', 'name2', 'b@b');
INSERT INTO QUESTION (TITLE, CONTENTS, WRITER_ID) VALUES ('test1', 'teeeeeest1', 1);
INSERT INTO QUESTION (TITLE, CONTENTS, WRITER_ID) VALUES ('test2', 'teeeeeest2', 2);
